# Generated by Django 3.1.5 on 2021-08-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210802_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
