# Generated by Django 3.2.5 on 2021-07-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210725_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured', models.FileField(upload_to='')),
                ('file_path', models.FilePathField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
            options={
                'db_table': 'captured',
            },
        ),
    ]
