# Generated by Django 3.2.5 on 2021-07-31 16:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_captured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captured',
            name='captured',
            field=models.FileField(upload_to=accounts.models.get_upload_path),
        ),
    ]
