# Generated by Django 3.2.5 on 2021-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210802_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'permissions': (('can_view', 'Can View user'), ('can_edit', 'Can Edit user'))},
        ),
        migrations.AlterField(
            model_name='captured',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='accounts',
            table=None,
        ),
    ]
