# Generated by Django 3.2.5 on 2021-08-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210806_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={},
        ),
        migrations.AlterModelTable(
            name='accounts',
            table='accounts',
        ),
    ]
